name: 'Configure AWS Credentials'
description: 'Assumes an AWS IAM role and configures AWS credentials for use in subsequent steps'
inputs:
  environment:
    description: 'Environment where to deploy the stack (dev, staging)'
    required: true
  stack-name:
    description: 'Name of the deployment stack'
    required: true
  pulumi-access-token:
    description: 'Pulumi access token'
    required: true
  aws-region:
    description: 'Region'
    required: true
runs:
  using: "composite"
  steps:
    - name: Get IAM role from Pulumi
      uses: Virtual-Finland-Development/pulumi-outputs-action@v1
      id: infra-iam-role
      with:
        organization: virtualfinland
        project: infrastructure
        stack: ${{ inputs.environment }}
        resource: DeployerIAMRole
        access-token: ${{ inputs.pulumi-access-token }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ steps.infra-iam-role.outputs.resource-output }}
        role-session-name: ${{ inputs.stack-name }}