name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: false
        default: dev

env:
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}

jobs:
  pulumi-preview:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Pulumi Configurations Unit Tests
        run: dotnet test ./VirtualFinland.Infrastructure.UnitTests --no-restore
      - name: Get IAM role from Pulumi
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: infra-iam-role
        with:
          organization: virtualfinland
          project: infrastructure
          stack: ${{ env.ENVIRONMENT }}
          resource: DeployerIAMRole
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ steps.infra-iam-role.outputs.resource-output }}
          role-session-name: infrastructure-deployer
      - uses: pulumi/actions@v5
        with:
          work-dir: ./VirtualFinland.Infrastructure
          command: preview
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/${{ env.ENVIRONMENT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
