name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pulumi-preview:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build Stack Features
        run: make -s -C ./VirtualFinland.KeyRotator build
      - name: Pulumi Key Rotator Unit Tests
        run: dotnet test ./VirtualFinland.KeyRotator.UnitTests --no-restore
      - name: Pulumi Configurations Unit Tests
        run: dotnet test ./VirtualFinland.Infrastructure.UnitTests --no-restore
      - name: Get IAM role from Pulumi
        uses: Virtual-Finland-Development/pulumi-outputs-action@v1
        id: infra-iam-role
        with:
          organization: virtualfinland
          project: infrastructure
          stack: dev
          resource: DeployerIAMRole
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ steps.infra-iam-role.outputs.resource-output }}
          role-session-name: infrastructure-test
      - uses: pulumi/actions@v4
        with:
          work-dir: ./VirtualFinland.Infrastructure
          command: preview
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
