name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where to deploy the stack (dev, staging)
        type: environment
        required: false
        default: dev

env:
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}

jobs:
  pulumi-preview:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Pulumi Configurations Unit Tests
        run: dotnet test ./VirtualFinland.Infrastructure.UnitTests --no-restore
      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - uses: pulumi/actions@v4
        with:
          work-dir: ./VirtualFinland.Infrastructure
          command: preview
          stack-name: ${{ secrets.PULUMI_ORGANIZATION }}/${{ env.ENVIRONMENT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
